site_name: Basic Weapons Wiki
site_url: https://example.com/
repo_url: https://github.com/Khazoda/basic-weapons
repo_name: basic weapons
nav:
  - Home: index.md
  - About: about.md
theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode