site_name: Basic Weapons Wiki
site_description: Find detailed information on the Basic Weapons mod for Minecraft.
site_url: https://basicweapons.khazoda.top/en/latest/
repo_url: https://github.com/Khazoda/basic-weapons
repo_name: basic weapons
nav:
  - Home: index.md
  - Weapons: 
    - weapons/dagger.md
    - weapons/hammer.md
    - weapons/club.md
    - weapons/quarterstaff.md
    - weapons/spear.md
  - Contributing:
    - contributing/index.md

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Khazoda
extra_css:
    - overrides.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.share
    - navigation.top
    - content.code.annotate
    - content.tooltips
    - navigation.footer
  